### ISSUE TITLE
Add a config for the whole "melee pulls player" mechanic.

### ISSUE THREAD

**Issue by Mackwell909** [Mirsario/TerrariaOverhaul#167]
There's this Overhaul feature that makes it so Melee attacks, when swung or strike an enemy, pull the player towards the target. This can be great at times! Emphasis on "at times" though. Sometimes, when you're fighting Wall of Flesh, for example, you can get pulled towards the already moving towards you wall, even behind him. This can make it difficult to fight him, even impossible, I dare say. So, I propose a solution. Add a config that can disable this feature, for the love of god PLEASE. I beg.

**Comment by Mirsario** [comment]
Late reply, but this is already present as `Melee.EnableAirCombat` on GitHub since PR 157, and will arrive in beta 12 whenever that gets released.
Here's [build instructions](https://github.com/Mirsario/TerrariaOverhaul#%EF%B8%8F-how-do-i-build-this), they're quite simple.

Also, I'm yet to finish the feature, it needs to listen to player's directional movement inputs a ton more. Already added that for swing velocity, but not air combat.
