### ISSUE TITLE
Lighting system?

### ISSUE THREAD

**Issue by Slimerblue22** [Mirsario/TerrariaOverhaul#20]
So I use HERO's Mod (https://forums.terraria.org/index.php?threads/heros-mod-terraria-creative-mode-server-management-and-over-25-tools.44650/) mainly to disable gravestones and the full bright/night vision. When using TerrariaOverhaul that light function doesn't seem to work anymore, so my question is does this mod change the lighting system and can it be reverted some way?

**Comment by Mirsario** [comment]
This mod includes a few amateurish optimizations for lighting, which I think just can't not screw things up like in your case with HERO's without becoming slower. Adding a toggle for it would probably be a hassle, since other optimizations are tied to use methods from this one. But I'm planning another shader-based lighting rewrite eventually, and that will most definitely be toggleable.
