### ISSUE TITLE
Sword's charge should be releasable at any time.

### ISSUE THREAD

**Issue by Shadowblitz16** [Mirsario/TerrariaOverhaul#254]
Sword's charge should be releasable at any time.

Axe could stay the same and possibly be a bit stronger due to needing to time it.

This could also add a difference between swords and axes.

**Comment by Mirsario** [comment]
Should be.. why exactly? "It would help me win" is not a valid argument. It's a fixed charge length by design, to introduce commitment and to have a rhythmical synchronization point for other mechanics' formed combination strategies.
https://discord.com/channels/339407372843876353/340670797020659733/1302935453892218919

**Comment by Shadowblitz16** [comment]
@Mirsario You seem like you really dislike me or your really dislike my suggestion and it won't matter what I say so it's pointless for me to argue.

**Comment by Mirsario** [comment]
Neither are the case, and the length of the linked Discord discussion proves otherwise. If you have new points not stated there you can send them to the same channel. What I dislike is "X should Y" statements with no context or design support, the mod has a (currently private) design document, with every decision argued for within it.
