### ISSUE TITLE
"Archery Overhaul" Issues

### ISSUE THREAD

**Issue by Hotmud9** [Mirsario/TerrariaOverhaul#46]
Most of the bows in the "Archery Overhaul" mod actually work really well with this mod, but there are a few conflicts:
1. The "Repeater Bow" is incorrectly turned into an actual repeater, instead of shooting two arrows in quick succession. Upgrading the bow into the "Clockwork Bow" fixes this issue, but upgrading it also creates another conflict.
2. When firing this bow, instead of firing 3 arrows at once, it shoots 5. When charging it with right-click, releasing with three arrows charged will only shoot 1 arrow in each direction, except for the middle, which still shoots 5.
3. The early-game crossbows that are added work fine, except for their alternate ability, which conflicts with this mod and will not function properly.

**Comment by USMP-lancer** [comment]
the repeater bow is because of how bow overhauls are applied, the repeaters and the regular bows both use arrows, so the repeaters have to have a special case, since they don't have bow in their name its easy, if arrow shooter has repeater in name, apply this overhaul instead,that's the issue, as for the second one, that's some strange coding artifact which should disappear in the 1.4  version
3 is just how its programmed, although in the 1.4 version there might be a change where the charged attacks can be rebound to fix this, it all depends on if someone makes a pr in the help wanted for it

**Comment by USMP-lancer** [comment]
hamgur

**Comment by Hotmud9** [comment]
> hamgur

Could you not?

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
