### ISSUE TITLE
Mod can't load | Error

### ISSUE THREAD

**Issue by P5yk3r** [Mirsario/TerrariaOverhaul#87]
Hi there
So, I installed Overhaul for 1.4 Alpha tModLoader 0.12, 13db301a, built 21.03.2022 and when I turn on Overhaul I see just error message.
Only I have this problem (seems like this) or this is bug?

Thank you in advance

![4M8_QJtI4TU](https://user-images.githubusercontent.com/102184980/159563148-8aaaebad-2ed5-494a-97ee-944cf75d25b2.jpg)

**Comment by Mirsario** [comment]
That's 1.3 Overhaul you're trying to load, on also the wrong 1.4 TML version (as 1.4 Overhaul uses special 1.4_mergedtesting builds instead of the official alpha version.)

If you're not looking to compile anything yourself - get both Overhaul and TML [from here](https://www.patreon.com/posts/61423321), instructions are also there. Future betas will be posted in the [Discord](http://discord.gg/RNGq9N8).
